apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "playground.producer" . }}-deployment
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      {{- include "playground.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "playground.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: producer
          image: "{{ .Values.producer.image.repository }}"
          imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
          env:
            - name: {{ .Values.producer.env.bootstrap_servers.name }}
              {{ $template := include "playground.kafka-svc" . }}
              {{ $port := printf "%s" .Values.kafka.service.port }}
              value: {{ printf "http://$s:$s" $template $port }}
            - name: {{ .Values.producer.env.directory.name }}
              value: {{ .Values.producer.env.directory.value }}
            - name: {{ .Values.producer.env.first_name.name }}
              value: {{ .Values.producer.env.first_name.value }}
            - name: {{ .Values.producer.env.last_name.name }}
              value: {{ .Values.producer.env.last_name.value }}
            - name: {{ .Values.producer.env.words.name }}
              value: {{ .Values.producer.env.words.value }}