apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-inf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-inf
      name: kafka-inf
  template:
    metadata:
      labels:
        app: kafka-inf
        name: kafka-inf
    spec:
      containers:
        - name: kafka-inf
          image: confluentinc/cp-kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-inf:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CREATE_TOPICS
              value: "our_kafka_topic:1:1"
            - name: TOPIC_NAME
              value: "our_kafka_topic"