version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    links:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOSTNAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  cassandraproc:
    image: cassandraproc
    container_name: cassandraproc
    depends_on:
      - cassandra
      - kafka
    links:
      - kafka
      - cassandra
    environment:
      auto_offset_reset: 'latest'
      group_id: 'consumer-group'
      enrich_cassproc_topic: 'enrich_cassproc'
      bootstrap_servers: 'kafka:29092'
      cassandra_url: cassandra
      cassandra_port: 7000
      cassandra_keyspace: kafka
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  esproc:
    image: esproc
    container_name: esproc
    depends_on:
      - elasticsearch
      - kafka
    links:
      - elasticsearch
      - kafka
    environment:
      offset_reset: 'latest'
      group_id: 'consumer-group'
      enrich_esproc_topic: 'enrich_esproc'
      bootstrap_servers: 'kafka:29092'
      elasticsearch_url: elasticsearch
      elasticsearch_port: 9200
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  kafka-producer:
    image: kafka-producer
    container_name: kafka-producer
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    environment:
      bootstrap_servers: 'kafka:29092'
      filesDir: '/src/main/resources/twitter'
      firstNamesFile: 'firstname.txt'
      lastNamesFile: 'surname.txt'
      wordsFile: 'words.txt'
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  cassandra:
    container_name: cassandra
    image: cassandra
    environment:
      cassandraUrl: '127.0.0.1'
      cassandraPort: '7000'
      cassandra_keyspace: 'kafka'
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "104"
    depends_on:
      - elasticsearch
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.8.1
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
volumes:
  elasticsearch-data:
    driver: local
